/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListingIdRouteImport } from './routes/listing.$id'
import { Route as ApiWebhooksStripeRouteImport } from './routes/api/webhooks/stripe'
import { Route as ApiStripeCreateSubscriptionCheckoutRouteImport } from './routes/api/stripe/create-subscription-checkout'
import { Route as ApiStripeCreateCustomerRouteImport } from './routes/api/stripe/create-customer'

const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingIdRoute = ListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: '/api/webhooks/stripe',
  path: '/api/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeCreateSubscriptionCheckoutRoute =
  ApiStripeCreateSubscriptionCheckoutRouteImport.update({
    id: '/api/stripe/create-subscription-checkout',
    path: '/api/stripe/create-subscription-checkout',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiStripeCreateCustomerRoute = ApiStripeCreateCustomerRouteImport.update({
  id: '/api/stripe/create-customer',
  path: '/api/stripe/create-customer',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/subscribe': typeof SubscribeRoute
  '/listing/$id': typeof ListingIdRoute
  '/api/stripe/create-customer': typeof ApiStripeCreateCustomerRoute
  '/api/stripe/create-subscription-checkout': typeof ApiStripeCreateSubscriptionCheckoutRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/subscribe': typeof SubscribeRoute
  '/listing/$id': typeof ListingIdRoute
  '/api/stripe/create-customer': typeof ApiStripeCreateCustomerRoute
  '/api/stripe/create-subscription-checkout': typeof ApiStripeCreateSubscriptionCheckoutRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/subscribe': typeof SubscribeRoute
  '/listing/$id': typeof ListingIdRoute
  '/api/stripe/create-customer': typeof ApiStripeCreateCustomerRoute
  '/api/stripe/create-subscription-checkout': typeof ApiStripeCreateSubscriptionCheckoutRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/subscribe'
    | '/listing/$id'
    | '/api/stripe/create-customer'
    | '/api/stripe/create-subscription-checkout'
    | '/api/webhooks/stripe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/subscribe'
    | '/listing/$id'
    | '/api/stripe/create-customer'
    | '/api/stripe/create-subscription-checkout'
    | '/api/webhooks/stripe'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/subscribe'
    | '/listing/$id'
    | '/api/stripe/create-customer'
    | '/api/stripe/create-subscription-checkout'
    | '/api/webhooks/stripe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SubscribeRoute: typeof SubscribeRoute
  ListingIdRoute: typeof ListingIdRoute
  ApiStripeCreateCustomerRoute: typeof ApiStripeCreateCustomerRoute
  ApiStripeCreateSubscriptionCheckoutRoute: typeof ApiStripeCreateSubscriptionCheckoutRoute
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$id': {
      id: '/listing/$id'
      path: '/listing/$id'
      fullPath: '/listing/$id'
      preLoaderRoute: typeof ListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/stripe': {
      id: '/api/webhooks/stripe'
      path: '/api/webhooks/stripe'
      fullPath: '/api/webhooks/stripe'
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/create-subscription-checkout': {
      id: '/api/stripe/create-subscription-checkout'
      path: '/api/stripe/create-subscription-checkout'
      fullPath: '/api/stripe/create-subscription-checkout'
      preLoaderRoute: typeof ApiStripeCreateSubscriptionCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/create-customer': {
      id: '/api/stripe/create-customer'
      path: '/api/stripe/create-customer'
      fullPath: '/api/stripe/create-customer'
      preLoaderRoute: typeof ApiStripeCreateCustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SubscribeRoute: SubscribeRoute,
  ListingIdRoute: ListingIdRoute,
  ApiStripeCreateCustomerRoute: ApiStripeCreateCustomerRoute,
  ApiStripeCreateSubscriptionCheckoutRoute:
    ApiStripeCreateSubscriptionCheckoutRoute,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
